[package]
name = "infomaniak-dyndns-wildcard"
version = "0.1.0"
edition = "2024"

[dependencies]
config = "0.14.1"
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = "1.0.219"
serde_json = "1.0"

[[bin]]
name = "infomaniak-dyndns-wildcard"
path = "src/main.rs"
