name: CI

on:
  push:
  workflow_dispatch:

jobs:
  test-build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4.1.7
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.1.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.4.0
      - name: Login to DockerHub
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKERHUB_DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKERHUB_DOCKER_REGISTRY_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6.3.0
        with:
          tags: itsalex/infomaniak-dyndns-wildcard:test-build-ci
          file: Dockerfile
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  pre-release:
    name: "Pre Release"
    if: ${{ github.repository == 'Its-Alex/infomaniak-dyndns-wildcard' && contains(github.ref, 'refs/heads/main') }}
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout project
        uses: actions/checkout@v4.1.7

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.1.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.4.0
      - name: Login to DockerHub
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKERHUB_DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKERHUB_DOCKER_REGISTRY_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6.3.0
        with:
          push: true
          tags: itsalex/infomaniak-dyndns-wildcard:latest
          file: Dockerfile
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"

  tagged-release:
    name: "Tagged Release"
    if: ${{ github.repository == 'Its-Alex/infomaniak-dyndns-wildcard' && contains(github.ref, 'refs/tags/v') }}
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout project
        uses: actions/checkout@v4.1.7

      - name: Generate version variable
        id: branch_name
        run: echo "TAG_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT


      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.1.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.4.0
      - name: Login to DockerHub
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKERHUB_DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKERHUB_DOCKER_REGISTRY_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6.3.0
        with:
          push: true
          tags: itsalex/infomaniak-dyndns-wildcard:${{ steps.branch_name.outputs.TAG_VERSION }}
          file: Dockerfile
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false