name: CI

on:
  push:
  workflow_dispatch:

jobs:
  check-rust-code:
    name: "Check rust code"
    runs-on: ubuntu-latest
    container: rust:1.87.0-bookworm
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Install Rust toolchain
        run: |
          rustup component add clippy
          rustup component add rustfmt
      - name: Run clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Run fmt
        run: cargo fmt --all -- --check
      - name: Run build
        run: cargo build --all-targets --all-features --verbose

  test-build-docker-image:
    name: "Test build docker image"
    if: ${{ !contains(github.ref, 'refs/heads/main') }}
    runs-on: ubuntu-latest
    needs: [check-rust-code]
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKERHUB_DOCKER_REGISTRY_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          tags: itsalex/infomaniak-dyndns-wildcard:test-build-ci
          file: Dockerfile
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  pre-release:
    name: "Pre release"
    if: ${{ github.repository == 'Its-Alex/infomaniak-dyndns-wildcard' && contains(github.ref, 'refs/heads/main') }}
    runs-on: "ubuntu-latest"
    needs: [check-rust-code]
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKERHUB_DOCKER_REGISTRY_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: itsalex/infomaniak-dyndns-wildcard:latest
          file: Dockerfile
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"

  tagged-release:
    name: "Tagged release"
    if: ${{ github.repository == 'Its-Alex/infomaniak-dyndns-wildcard' && contains(github.ref, 'refs/tags/v') }}
    runs-on: "ubuntu-latest"
    needs: [check-rust-code]
    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Generate version variable
        id: branch_name
        run: echo "TAG_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT


      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKERHUB_DOCKER_REGISTRY_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: itsalex/infomaniak-dyndns-wildcard:${{ steps.branch_name.outputs.TAG_VERSION }}
          file: Dockerfile
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false